### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by nullptr2nullptr** [KGrewal1/optimisers#3]
Hi @KGrewal1, this looks like a really cool addition to the Candle ecosystem!

I noticed a small typo in the name of your repo - and am not sure if it is intentional? I think that you can change this in the Settings tab.

**Comment by KGrewal1** [comment]
If this is s vs z in optimisers, I tend to try to stick to s as it is the British spelling, and as I'm writing up stuff for submission I tend to try to stick to the Britsh one. If it's a different typo, I haven't noticed it

**Comment by nullptr2nullptr** [comment]
I meant the is the optim**s**ers "typo". Thanks for the clarification!
